
@startuml
actor 图书管理员
boundary 账号判断
control 业务控制
database 数据库


autonumber
activate 图书管理员
activate 账号判断
图书管理员 -> 账号判断:输入读者账号信息
activate 业务控制
账号判断 -> 业务控制 : 获取账号信息

activate 数据库
业务控制 -> 数据库 : 比对账号密码合法性
数据库 --> 业务控制 : 账号合法或者不合法
业务控制 --> 账号判断 : 返回操作结果
账号判断 --> 图书管理员 : 返回账号判断结果
deactivate 账号判断
opt 还书账号合法
图书管理员 -> 业务控制 : 输入归还图书信息
业务控制 -> 数据库 : 删除借阅信息
业务控制 -> 数据库 : 修改图书库存
业务控制 -> 数据库 : 查询借阅是否超时
数据库 --> 业务控制 : 返回操作结果
deactivate 数据库

业务控制 --> 图书管理员 : 返回归还结果
deactivate 业务控制
deactivate 图书管理员
end
@enduml