@startuml
|图书管理员|
start
repeat
	:管理员登录;
	|系统|
	:判断账号密码正确;
repeat while (登录成功?)
|图书管理员|
repeat
	:输入归还账号;
	|系统|
	:判断账号合法性;
repeat while (输入合法?)
|系统|
if (账号是否借阅该书超时) then (未超时)
	:归还图书;
	detach
else
	:返回罚款信息;
endif
:修改库存;

|图书管理员|
:查看结果;

stop
@enduml