@startuml
|读者|
start
repeat
	:读者登录;
	|系统|
	:判断帐号密码正确;
repeat while (登陆成功?)
|读者|
:预订图书;
|系统|
if(库存不足?) then (不足)
	:库存不足，中止预订，返回库存信息;
	detach
else
	:库存减一;
:返回预订信息;
|读者|
:预订成功;
stop
@enduml